// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_section: dynamic(() => import("./BlogSection")),
  hero: dynamic(() => import("./Hero")),
  travel_grid: dynamic(() => import("./TravelGrid")),
};
